/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.text.SimpleDateFormat;

import java.util.Date;
import Controlador.Administrar_Aeronave;

import Database.Conexion;
import Modelo.Usuario;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import libreriaupperessential.LibreriaUpperEssential; 
/**
 *
 * @author jordans
 */
public class IngresarAeronave extends javax.swing.JFrame {

    /**
     * Creates new form IngresarAeronave
     */
    public IngresarAeronave() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtmatricula = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        cmbestado = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txthorasvuelo = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtdiasvuelo = new javax.swing.JTextPane();
        btningresar = new javax.swing.JButton();
        cmbtiponave = new javax.swing.JComboBox<>();
        cmbdiaaero = new javax.swing.JComboBox<>();
        cmbaeromes = new javax.swing.JComboBox<>();
        txtanio = new javax.swing.JTextField();
        cmbdiainspec = new javax.swing.JComboBox<>();
        cmbmesinspec = new javax.swing.JComboBox<>();
        txtanioinsp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Ingresar Aeronave");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Tipo Aeronave");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Ingrese Matrícula");

        jScrollPane1.setViewportView(txtmatricula);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Estado");

        cmbestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "Disponible", "No Disponible" }));
        cmbestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbestadoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Fecha Aeronavegabilidad");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Horas de Vuelo");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Fecha de Inspeccion Anual");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Días de Vuelo");

        jScrollPane2.setViewportView(txthorasvuelo);

        jScrollPane3.setViewportView(txtdiasvuelo);

        btningresar.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        btningresar.setText("Ingresar Aeronave");
        btningresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresarActionPerformed(evt);
            }
        });

        cmbtiponave.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "Helicoptero", "Aeronave" }));
        cmbtiponave.setToolTipText("");
        cmbtiponave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbtiponaveActionPerformed(evt);
            }
        });

        cmbdiaaero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " ", " " }));

        cmbaeromes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes\t", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre", " " }));

        txtanio.setText("Año");

        cmbdiainspec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " ", " " }));

        cmbmesinspec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes\t", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre", " " }));

        txtanioinsp.setText("Año");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btningresar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(139, 139, 139)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(43, 43, 43)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cmbestado, 0, 131, Short.MAX_VALUE)
                                        .addComponent(cmbtiponave, 0, 131, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1)
                                        .addComponent(jScrollPane2)
                                        .addComponent(jScrollPane3)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(cmbdiaaero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(cmbaeromes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtanio, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cmbdiainspec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cmbmesinspec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtanioinsp, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbtiponave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbdiaaero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbaeromes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbdiainspec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbmesinspec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtanioinsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btningresar)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbestadoActionPerformed

    private void btningresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresarActionPerformed

 Conexion con = new Conexion();
        con.conectar();
       
    String matricula = txtmatricula.getText();
    String horasvuelo = txthorasvuelo.getText();
    String diasvuelo = txtdiasvuelo.getText();
    String tiponave = ""+cmbtiponave.getSelectedItem();
    String estado = ""+cmbestado.getSelectedItem();
     String diaaero = ""+cmbdiaaero.getSelectedItem();
    String mesaero = ""+cmbaeromes.getSelectedItem();
    String mesinsp;
    String anioaero= txtanio.getText();
    String diainspec = ""+cmbdiainspec.getSelectedItem();
    String anioinspec=txtanioinsp.getText();

        switch (estado) {
            case "Seleccione:":
                
                 JOptionPane.showMessageDialog(null, "Seleccione estado!!!", "Ventana Error Datos", JOptionPane.ERROR_MESSAGE);
                break;
            case "Disponible":
                estado="V";
                break;
            default:
                estado="M";
                break;
        }
   
//String formato = fechanave.getDateFormatString();
//Date date = fechanave.getDate();
//SimpleDateFormat sdf = new SimpleDateFormat(formato);
//String fechaaeronavegabilidad = String.valueOf(sdf.format(date));
//
//String formato2 = fechaanual.getDateFormatString();
//Date date2 = fechaanual.getDate();
//SimpleDateFormat sdfs = new SimpleDateFormat(formato2);
//String fechaanual = String.valueOf(sdfs.format(date2));

Administrar_Aeronave ingresar = new Administrar_Aeronave();

        if (tiponave.equals("Helicoptero")) {
            tiponave="1";
            
        }else{
             tiponave="2";
        }
        
         if (cmbaeromes.getSelectedItem().equals("Enero")) {
            mesaero="01";
            
        }else if(cmbaeromes.getSelectedItem().equals("Febrero")) {
             mesaero="02";
        }  else if(cmbaeromes.getSelectedItem().equals("Marzo")) {
             mesaero="03";
        }else if(cmbaeromes.getSelectedItem().equals("Abril")) {
             mesaero="04";
        }
         else if(cmbaeromes.getSelectedItem().equals("Mayo")) {
             mesaero="05";
        }
         else if(cmbaeromes.getSelectedItem().equals("Junio")) {
             mesaero="06";
        }
         else if(cmbaeromes.getSelectedItem().equals("Julio")) {
             mesaero="07";
        }
         else if(cmbaeromes.getSelectedItem().equals("Agosto")) {
             mesaero="08";
        }
         else if(cmbaeromes.getSelectedItem().equals("Septiembre")) {
             mesaero="09";
        }
         else if(cmbaeromes.getSelectedItem().equals("Octubre")) {
             mesaero="10";
        }
         else if(cmbaeromes.getSelectedItem().equals("Noviembre")) {
             mesaero="11";
        }
         else if(cmbaeromes.getSelectedItem().equals("Diciembre")) {
             mesaero="12";
        }
           if (cmbmesinspec.getSelectedItem().equals("Enero")) {
            mesinsp="01";
            
        }else if(cmbmesinspec.getSelectedItem().equals("Febrero")) {
             mesinsp="02";
        }  else if(cmbmesinspec.getSelectedItem().equals("Marzo")) {
             mesinsp="03";
        }else if(cmbmesinspec.getSelectedItem().equals("Abril")) {
             mesinsp="04";
        }
         else if(cmbmesinspec.getSelectedItem().equals("Mayo")) {
             mesinsp="05";
        }
         else if(cmbmesinspec.getSelectedItem().equals("Junio")) {
             mesinsp="06";
        }
         else if(cmbmesinspec.getSelectedItem().equals("Julio")) {
             mesinsp="07";
        }
         else if(cmbmesinspec.getSelectedItem().equals("Agosto")) {
             mesinsp="08";
        }
         else if(cmbmesinspec.getSelectedItem().equals("Septiembre")) {
             mesinsp="09";
        }
         else if(cmbmesinspec.getSelectedItem().equals("Octubre")) {
             mesinsp="10";
        }
         else if(cmbmesinspec.getSelectedItem().equals("Noviembre")) {
             mesinsp="11";
        }
         else if(cmbmesinspec.getSelectedItem().equals("Diciembre")) {
             mesinsp="12";
        }
           int foo = Integer.parseInt(diaaero);
          if(foo<10){
              diaaero="0"+diaaero;
          } 
           String fecha_aeronave =diaaero+"/"+mesaero+"/"+anioaero;
           
//         Date fechaaeronave = null;
//        SimpleDateFormat fecha_nacimiento = new SimpleDateFormat("dd/MM/yyyy");
//        String dateInString = fecha_aeronave;
//
//        try {
//
//            fechaaeronave = fecha_nacimiento.parse(dateInString);
//            
//
//        } catch (ParseException e) {
//            
//            JOptionPane.showMessageDialog(null, "mensaje de error: "+e);
//        }
         
//       
//         java.sql.Date datito = new java.sql.Date(fechanave.getDate().getTime());
//         
//ingresar.ingresarAeronave(WIDTH, matricula, 0, date2, date2, TOP_ALIGNMENT, TEXT_CURSOR, componentes);
       // JOptionPane.showMessageDialog(null,"matricula  "+matricula+"tipo nave "+ Integer.parseInt(tiponave) +"  estado "+estado+" fecha aeronavegabilidad "+fecha_aeronave);
       
     con.escribir("INSERT INTO aeronaves  VALUES (21,"+matricula+","+Integer.parseInt(tiponave)+","+estado+","+"02/09/25,01/08/16"+","+Integer.parseInt(horasvuelo)+","+Integer.parseInt(diasvuelo)+")");
//        // TODO add your handling code here:
    }//GEN-LAST:event_btningresarActionPerformed

    private void cmbtiponaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbtiponaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtiponaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarAeronave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarAeronave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarAeronave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarAeronave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarAeronave().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btningresar;
    private javax.swing.JComboBox<String> cmbaeromes;
    private javax.swing.JComboBox<String> cmbdiaaero;
    private javax.swing.JComboBox<String> cmbdiainspec;
    private javax.swing.JComboBox<String> cmbestado;
    private javax.swing.JComboBox<String> cmbmesinspec;
    private javax.swing.JComboBox<String> cmbtiponave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtanio;
    private javax.swing.JTextField txtanioinsp;
    private javax.swing.JTextPane txtdiasvuelo;
    private javax.swing.JTextPane txthorasvuelo;
    private javax.swing.JTextPane txtmatricula;
    // End of variables declaration//GEN-END:variables
}
